#!/usr/bin/env python

# Copyright (c) 2019 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

import glob
import os
import sys

try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

import random
import time


def main():
    actor_list = []

    # In this tutorial script, we are going to add a vehicle to the simulation
    # and let it drive in autopilot. We will also create a camera attached to
    # that vehicle, and save all the images generated by the camera to disk.

    try:
        # First of all, we need to create the client that will send the requests
        # to the simulator. Here we'll assume the simulator is accepting
        # requests in the localhost at port 2000.
        client = carla.Client('localhost', 2000)
        client.set_timeout(2.0)

        # Once we have a client we can retrieve the world that is currently
        # running.
        # world = client.get_world()
        world = client.load_world('smart_intersection')

        # find all waypoints 
        carla_map = world.get_map()
        spawn_transforms = carla_map.get_spawn_points()

        # mark wpt
        for i, spawn_transform in enumerate(spawn_transforms): 
            location = spawn_transform.location
            wpt_index = 'wpt-' + str(i+1)
            # draw string
            world.debug.draw_string(
                location, 
                wpt_index, 
                draw_shadow=False,
                life_time=9999)

        # mark origin point (i.e., x,y = (0,0); z is lifted for display)
        origin_loc = carla.Location(x=0.0, y=0.0, z=3.0)
        # draw origin
        world.debug.draw_string(
                origin_loc, 
                'map-origin', 
                draw_shadow=False, 
                life_time=9999)
        

        time.sleep(5)

    finally:

        print('destroying actors')
        camera.destroy()
        client.apply_batch([carla.command.DestroyActor(x) for x in actor_list])
        print('done.')


if __name__ == '__main__':

    main()
